[build]
  publish = "."

[[headers]]
  for = "/proxy/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"

[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    Referrer-Policy = "strict-origin-when-cross-origin"
