[build]
  publish = "."
  functions = "netlify/functions"

[[edge_functions]]
  function = "inject-env"
  path = "/*"

[[redirects]]
  from = "/proxy/*"
  to = "/.netlify/functions/proxy/:splat"
  status = 200

[[redirects]]
  from = "/s=*"
  to = "/index.html"
  status = 200
